# Generated by Django 4.1.4 on 2023-01-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='address',
            new_name='address1',
        ),
    ]
