# Generated by Django 4.1.4 on 2023-01-07 06:06

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'shop-data.json'
def load_data(apps, schema_editor):
    Shop = apps.get_model('geolocation', 'Shop')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile), encoding='utf-8') as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Shop(name=name, location = location).save()
            except KeyError:
                pass     

class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_rename_address_shop_address1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='address1',
            new_name='address',
        ),
        migrations.RunPython(load_data)
    ]
