# Generated by Django 4.1.4 on 2023-01-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpwd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpwd',
            name='email1',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpwd',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
